include:
  - component: $CI_SERVER_HOST/CleverCloud/clever-cloud-pipeline/deploy-to-prod@2.0.3
    inputs:
      stage: release
      environment: staging
      step_name: deploy output_worker to staging
      app_id: $CLEVERCLOUD_STAGING_OUTPUT_WORKER_ID
      when: manual
  - component: $CI_SERVER_HOST/CleverCloud/clever-cloud-pipeline/deploy-to-prod@2.0.3
    inputs:
      stage: release
      environment: production
      step_name: deploy output_worker to production
      app_id: $CLEVERCLOUD_PRODUCTION_OUTPUT_WORKER_ID
      when: manual

output_worker.check:
  stage: test
  dependencies: []
  image: rust:$RUST_VERSION
  rules:
    - changes:
        - output-worker/**/*
        - sentry-integration/**/*
        - Cargo.*
  variables:
    SQLX_OFFLINE: "true"
  services:
    - postgres:$PG_VERSION
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
    - wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-linux-x86_64.zip && mkdir protoc && unzip protoc.zip -d protoc/
    - export PROTOC="$(realpath ./protoc/bin/protoc)"
  script:
    - pushd output-worker
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test
