//! Every target reads every document of the shared corpus it is a contract for, and every document
//! is a contract for somebody.
//!
//! The corpus at `clients/conformance` only holds a target up for as long as that target's own
//! suite opens it. A document nobody reads is a contract nobody honours, and it fails in the
//! quietest way there is: every suite stays green while the clients drift apart. That is the same
//! silent divergence the corpus exists to kill, one level up.
//!
//! What this checks, exactly: for every target of the registry, the file name of every document it
//! is held to is written inside a literal — between quotes, or after a path separator and before a
//! quote — in a hand-written source file of that target's own language, under the client the target
//! lands in; and the same suite writes the corpus directory the same way, so the documents are read
//! from the one committed copy rather than transcribed into the suite. What surrounds the name is
//! what tells a line that opens a document from a line that merely reads like one: `request.json`
//! is a document here and a builder call in `request = request.json(&body)`, and prose mentioning a
//! document is not a line reading it.
//!
//! Both sides are discovered. The documents are whatever the corpus directory holds, the targets
//! are whatever [`targets`] carries, and a target's client is the ancestor of its root that sits
//! beside the corpus — `clients/go/generated` is generated by the `go` target, so `clients/go` is
//! where its suite lives. Nothing about any of the three is written down here, so a document added
//! to the corpus and a target added to the registry are both carried without this file being
//! touched.
//!
//! Which documents apply to which target is read off the registry, where each target states it as
//! [`Contract`]. A client of its own is held to [`Contract::Whole`], which is whatever the corpus
//! comes to hold rather than a list that has to be widened with it. A target whose client takes
//! part in only some of the contract names the documents it does take part in, and the run says by
//! name which those are: the MCP server sends requests like every other client and is held to what
//! they carry, while a retry rule, a signature vector and a payload bound describe nothing it has —
//! holding it to those would make this guard wrong rather than strict. What it cannot be is silent.
//! A document no target is held to fails here, so a clause cannot be dropped by every target at
//! once claiming it belongs to somebody else, and a target claiming a document its suite does not
//! read fails as any other unread document does.
//!
//! What it deliberately does not check is that a suite *acts* on what it read: that is each
//! target's own business, and each proves it by driving its client against a socket. This is the
//! coarse guard the corpus lacked. It cannot tell a suite that reads a document well from one that
//! reads it badly, but it does stop a target from never opening it at all.
//!
//! Naming the document is the rule rather than reading the directory generically, which is the one
//! trade this makes: a suite that walked the corpus and named nothing would fail here on documents
//! it does in fact read. Naming them is what every suite does today, it is what a reader of one
//! suite can check by eye, and the refusal says what to do about it.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

use hook0_sdkgen::targets::{Contract, Target, targets};
use tempfile::TempDir;

/// Where the corpus every target reads sits, from the crate this suite runs out of.
const CORPUS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../conformance");

/// Where the targets land, from the crate this suite runs out of.
const REPOSITORY_ROOT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");

/// What a directory says it does not track, which is where the walk below stops.
const IGNORE_FILE: &str = ".gitignore";

/// Largest number of documents the corpus may hold. One above this is a directory that grew into
/// something other than a contract.
const MAX_DOCUMENTS: usize = 32;

/// Largest number of clients sitting beside the corpus.
const MAX_CLIENTS: usize = 32;

/// Deepest a hand-written file may sit under a client before the walk gives up.
const MAX_SUITE_DEPTH: usize = 8;

/// Largest number of entries walked under one client before the walk gives up.
const MAX_SUITE_ENTRIES: usize = 4096;

/// Largest hand-written file read back, in bytes.
const MAX_SUITE_FILE_BYTES: u64 = 512 * 1024;

/// Largest a client's whole hand-written suite may come to, in bytes.
const MAX_SUITE_BYTES: u64 = 8 * 1024 * 1024;

/// Largest ignore file read back, in bytes.
const MAX_IGNORE_BYTES: u64 = 16 * 1024;

/// How far up from a target root the client holding it is looked for.
const MAX_ANCESTRY: usize = 16;

/// The repository, with nothing left in the path to resolve.
fn repository() -> PathBuf {
    fs::canonicalize(REPOSITORY_ROOT).expect("the repository the targets land in is reachable")
}

/// The corpus, with nothing left in the path to resolve.
fn corpus() -> PathBuf {
    fs::canonicalize(CORPUS).expect("the corpus the targets read is reachable")
}

/// What the corpus holds, walked rather than named, so a document added to it is carried here
/// without this file being told about it.
fn documents(corpus: &Path) -> BTreeSet<String> {
    let mut documents = BTreeSet::new();

    for entry in fs::read_dir(corpus).expect("the corpus directory is readable") {
        let entry = entry.expect("every entry of the corpus is readable");
        let kind = entry
            .file_type()
            .expect("every entry of the corpus is a file or not");
        if !kind.is_file() {
            continue;
        }
        assert!(
            documents.len() < MAX_DOCUMENTS,
            "the corpus holds more than the {MAX_DOCUMENTS} documents read back"
        );
        documents.insert(entry.file_name().to_string_lossy().into_owned());
    }

    assert!(
        !documents.is_empty(),
        "{} holds no document, so this guard would hold every target to nothing",
        corpus.display()
    );
    documents
}

/// Which documents of the corpus that target is held to.
///
/// [`Contract::Whole`] is every document there is, so a client stating it picks up one added to the
/// corpus tomorrow without its registry entry being touched. [`Contract::Only`] names them, and two
/// ways of naming nothing are refused rather than quietly holding the target to nothing: a name
/// that is not a document, which is a clause misspelled in the registry, and no name at all, which
/// is the wholesale exemption that let the MCP client drop two headers unnoticed. Either would let
/// a target off the part of the contract it was meant to be held to, which is the failure this
/// whole guard exists to catch.
fn held_to<'a>(
    target: &Target,
    documents: &'a BTreeSet<String>,
) -> Result<BTreeSet<&'a str>, String> {
    match target.contract {
        Contract::Whole => Ok(documents.iter().map(String::as_str).collect()),
        Contract::Only([]) => Err(format!(
            "target `{}` is held to no document of the corpus at all, which is not something this \
             guard can be told: name what its client does take part in, or say why the corpus is a \
             contract about nothing it does and take this check apart deliberately",
            target.name,
        )),
        Contract::Only(named) => named
            .iter()
            .map(|claimed| {
                documents.get(*claimed).map(String::as_str).ok_or_else(|| {
                    format!(
                        "target `{}` is held to `{claimed}`, which is not a document of the \
                         corpus: it holds {}",
                        target.name,
                        listed(&documents.iter().map(String::as_str).collect::<Vec<&str>>()),
                    )
                })
            })
            .collect(),
    }
}

/// Where a target's own suite sits: the client its generated half lands in.
///
/// The corpus sits beside the clients, so the client of a target is the ancestor of its root whose
/// parent is the directory the corpus sits in. A target landing anywhere else says so rather than
/// being quietly skipped, since a target nothing can be found for is a target nothing holds.
fn client_of(target: &Target, repository: &Path, clients: &Path) -> Result<PathBuf, String> {
    let landed = repository.join(target.root);
    let mut candidate = landed.as_path();

    for _ in 0..MAX_ANCESTRY {
        match candidate.parent() {
            Some(parent) if parent == clients => return Ok(candidate.to_path_buf()),
            Some(parent) => candidate = parent,
            None => break,
        }
    }

    Err(format!(
        "target `{}` lands at {}, which sits under no client beside the corpus at {}, so this \
         guard cannot tell where its suite is",
        target.name,
        target.root,
        clients.display()
    ))
}

/// The directory names the repository already says are not source.
///
/// Read out of the ignore files rather than written down here: what a package manager or a build
/// leaves behind is declared there once, and a walk that descended into it would read somebody
/// else's tests and call them this target's. Only the plain names are taken — a pattern, a negation
/// or a name with a path in it says something this walk does not need to understand.
fn not_source(repository: &Path, clients: &Path) -> Result<BTreeSet<String>, String> {
    let mut declaring = vec![repository.join(IGNORE_FILE)];

    let entries = fs::read_dir(clients)
        .map_err(|err| format!("{} cannot be read: {err}", clients.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("{} cannot be read: {err}", clients.display()))?;
        let kind = entry
            .file_type()
            .map_err(|err| format!("{} cannot be looked at: {err}", entry.path().display()))?;
        if !kind.is_dir() {
            continue;
        }
        if declaring.len() > MAX_CLIENTS {
            return Err(format!(
                "more than the {MAX_CLIENTS} clients read back sit beside the corpus"
            ));
        }
        declaring.push(entry.path().join(IGNORE_FILE));
    }

    let mut ignored = BTreeSet::new();
    for path in declaring {
        let Ok(metadata) = fs::metadata(&path) else {
            continue;
        };
        if metadata.len() > MAX_IGNORE_BYTES {
            return Err(format!(
                "{} is {} bytes long, above the {MAX_IGNORE_BYTES} read back",
                path.display(),
                metadata.len()
            ));
        }

        let written = fs::read_to_string(&path)
            .map_err(|err| format!("{} cannot be read: {err}", path.display()))?;
        for line in written.lines() {
            let line = line.trim();
            if line.is_empty()
                || line.starts_with('#')
                || line.starts_with('!')
                || line.contains(['*', '?', '['])
            {
                continue;
            }
            let name = line.trim_matches('/');
            if name.is_empty() || name.contains('/') {
                continue;
            }
            ignored.insert(name.to_owned());
        }
    }

    Ok(ignored)
}

/// What one target's hand-written suite holds.
///
/// Every file of the target's own language under its client, less the generated half — which is
/// written by the emitter and could name a document without anybody having read one — and less what
/// the repository does not track. Nothing is trimmed to fit: a client above a ceiling is refused
/// with the ceiling it crossed, since a suite read halfway would be a guard that passes on the half
/// it happened to reach.
fn suite_of(
    client: &Path,
    generated: &Path,
    extension: &str,
    ignored: &BTreeSet<String>,
) -> Result<Vec<String>, String> {
    let mut read = Vec::new();
    let mut visited = 0usize;
    let mut total = 0u64;
    let mut stack = vec![(client.to_path_buf(), 0usize)];

    while let Some((directory, depth)) = stack.pop() {
        if depth > MAX_SUITE_DEPTH {
            return Err(format!(
                "{} sits {depth} directories under the client, below the {MAX_SUITE_DEPTH} walked",
                directory.display()
            ));
        }

        let entries = fs::read_dir(&directory)
            .map_err(|err| format!("{} cannot be read: {err}", directory.display()))?;
        for entry in entries {
            let entry =
                entry.map_err(|err| format!("{} cannot be read: {err}", directory.display()))?;
            visited += 1;
            if visited > MAX_SUITE_ENTRIES {
                return Err(format!(
                    "more than the {MAX_SUITE_ENTRIES} entries walked sit under {}",
                    client.display()
                ));
            }

            let path = entry.path();
            let kind = entry
                .file_type()
                .map_err(|err| format!("{} cannot be looked at: {err}", path.display()))?;

            // A link is never descended and never read: what it points at is walked where it lives
            // or not at all.
            if kind.is_dir() {
                let name = entry.file_name().to_string_lossy().into_owned();
                if path == generated || ignored.contains(&name) {
                    continue;
                }
                stack.push((path, depth + 1));
                continue;
            }
            if !kind.is_file() || path.extension() != Some(OsStr::new(extension)) {
                continue;
            }

            let metadata = entry
                .metadata()
                .map_err(|err| format!("{} cannot be looked at: {err}", path.display()))?;
            if metadata.len() > MAX_SUITE_FILE_BYTES {
                return Err(format!(
                    "{} is {} bytes long, above the {MAX_SUITE_FILE_BYTES} read back",
                    path.display(),
                    metadata.len()
                ));
            }
            total += metadata.len();
            if total > MAX_SUITE_BYTES {
                return Err(format!(
                    "the suite under {} comes to more than the {MAX_SUITE_BYTES} bytes read back",
                    client.display()
                ));
            }

            let bytes = fs::read(&path)
                .map_err(|err| format!("{} cannot be read: {err}", path.display()))?;
            read.push(
                String::from_utf8(bytes)
                    .map_err(|err| format!("{} is not UTF-8: {err}", path.display()))?,
            );
        }
    }

    Ok(read)
}

/// Which of the documents a target is held to the suite never names.
fn unread<'a>(held_to: &BTreeSet<&'a str>, suite: &[String]) -> Vec<&'a str> {
    held_to
        .iter()
        .copied()
        .filter(|document| !names(suite, document))
        .collect()
}

/// What a name a suite opens something by is written between.
const DELIMITERS: [char; 4] = ['"', '\'', '`', '/'];

/// Whether anything the suite holds names that path, as the thing it opens rather than as something
/// a line happens to read like.
///
/// The name has to sit inside a literal: what precedes it is a quote or a path separator, and so is
/// what follows. `request = request.json(&body)` builds a request out of a body, and a plain search
/// would read it as the MCP server opening `request.json` — the two are told apart by what surrounds
/// the name, which needs nothing written down about either. Prose is told apart the same way: a
/// comment mentioning `retry.json` in passing is not a line that reads it.
fn names(suite: &[String], subject: &str) -> bool {
    suite.iter().any(|file| {
        file.match_indices(subject).any(|(at, _)| {
            let before = file[..at].chars().next_back();
            let after = file[at + subject.len()..].chars().next();
            matches!(before, Some(character) if DELIMITERS.contains(&character))
                && matches!(after, Some(character) if DELIMITERS.contains(&character))
        })
    })
}

/// The names of a list, as a message reads them out.
fn listed(subjects: &[&str]) -> String {
    subjects
        .iter()
        .map(|subject| format!("`{subject}`"))
        .collect::<Vec<String>>()
        .join(", ")
}

/// The path as it is written in the repository, which is how a message names it.
fn under_repository(path: &Path, repository: &Path) -> String {
    path.strip_prefix(repository)
        .unwrap_or(path)
        .display()
        .to_string()
}

/// The guard: a document of the corpus that a target never opens is a clause of the contract that
/// target is not held to, and nothing else would ever say so.
#[test]
fn every_target_reads_every_document_of_the_shared_corpus() {
    let repository = repository();
    let corpus = corpus();
    let clients = corpus
        .parent()
        .expect("the corpus sits beside the clients that read it");
    let directory = corpus
        .file_name()
        .and_then(OsStr::to_str)
        .expect("the corpus directory is named");
    let documents = documents(&corpus);
    let ignored = not_source(&repository, clients).unwrap_or_else(|reason| panic!("{reason}"));

    // What each target's suite holds and which documents it answers for, and — the other way round
    // — which targets read each document, so a refusal can point at the suites that already do.
    let mut suites: Vec<(&Target, PathBuf, BTreeSet<&str>, Vec<String>)> = Vec::new();
    let mut absent: Vec<&str> = Vec::new();
    let mut partly: Vec<(&str, Vec<&str>)> = Vec::new();
    let mut claimed: BTreeSet<&str> = BTreeSet::new();
    let mut readers: BTreeMap<&str, Vec<&str>> = BTreeMap::new();

    for target in targets() {
        let client =
            client_of(target, &repository, clients).unwrap_or_else(|reason| panic!("{reason}"));
        let held_to = held_to(target, &documents).unwrap_or_else(|reason| panic!("{reason}"));
        if !client.is_dir() {
            absent.push(target.name);
            continue;
        }

        let generated = repository.join(target.root);
        let suite = suite_of(&client, &generated, target.language.extension, &ignored)
            .unwrap_or_else(|reason| {
                panic!(
                    "the suite of target `{}` cannot be read: {reason}",
                    target.name
                )
            });

        if held_to.len() < documents.len() {
            partly.push((target.name, held_to.iter().copied().collect()));
        }
        for document in &held_to {
            claimed.insert(document);
            if names(&suite, document) {
                readers.entry(document).or_default().push(target.name);
            }
        }
        suites.push((target, client, held_to, suite));
    }

    // A target whose client is not written yet is not held to a contract it could not read, but it
    // is named here so that being absent is a thing somebody can see rather than a way out.
    println!(
        "{} of the {} targets are held to what they answer for of the {} documents of {}",
        suites.len(),
        targets().len(),
        documents.len(),
        under_repository(&corpus, &repository)
    );
    if !absent.is_empty() {
        println!(
            "no client is written yet for {}, so nothing holds {} to the corpus",
            listed(&absent),
            if absent.len() == 1 { "it" } else { "them" }
        );
    }
    for (target, held_to) in &partly {
        println!(
            "`{target}` takes part in {} of the corpus and is held to nothing else",
            listed(held_to)
        );
    }
    assert!(
        !suites.is_empty(),
        "no target under {} is a client this corpus is a contract for, so this guard held nothing",
        clients.display()
    );

    let mut refused: Vec<(&str, String)> = Vec::new();
    for (target, client, held_to, suite) in &suites {
        let client = under_repository(client, &repository);
        let extension = target.language.extension;
        let held_to_names: Vec<&str> = held_to.iter().copied().collect();

        if suite.is_empty() {
            refused.push((
                target.name,
                format!(
                    "target `{}` carries no hand-written `.{extension}` file under {client}, so it \
                 reads none of {}.\n  \
                 Write its suite there and drive this client against the corpus, as the suites of \
                 the other targets do.",
                    target.name,
                    listed(&held_to_names),
                ),
            ));
            continue;
        }

        let unread = unread(held_to, suite);
        if unread.len() == held_to.len() {
            refused.push((
                target.name,
                format!(
                    "target `{}` reads none of {} of the shared corpus.\n  \
                 Its suite is the hand-written `.{extension}` files under {client}, and not one of \
                 them opens a document of {}.\n  \
                 Read them there and hold this client against what they declare, as the suites of \
                 the targets that do read them.",
                    target.name,
                    listed(&held_to_names),
                    under_repository(&corpus, &repository),
                ),
            ));
            continue;
        }

        if !unread.is_empty() {
            let reading: Vec<&str> = unread
                .iter()
                .flat_map(|document| readers.get(document))
                .flatten()
                .copied()
                .collect::<BTreeSet<&str>>()
                .into_iter()
                .collect();
            let already = if reading.is_empty() {
                "no target reads them, so this part of the contract holds nobody up".to_owned()
            } else {
                format!("{} already read them", listed(&reading))
            };

            refused.push((
                target.name,
                format!(
                    "target `{}` does not read {} of the shared corpus.\n  \
                 Its suite is the hand-written `.{extension}` files under {client}, and none of \
                 them names {}.\n  \
                 {already}: read the same documents there and hold this client against what they \
                 declare.",
                    target.name,
                    listed(&unread),
                    if unread.len() == 1 { "it" } else { "them" },
                ),
            ));
        }

        if !names(suite, directory) {
            refused.push((target.name, format!(
                "target `{}` names documents of the corpus but never says where they are read \
                 from: no hand-written `.{extension}` file under {client} mentions `{directory}`.\n  \
                 A suite that does not reach {} is held against a copy of the contract rather than \
                 against the contract.",
                target.name,
                under_repository(&corpus, &repository),
            )));
        }
    }

    // Every target is reported at once, since a corpus one target stopped reading is rarely the
    // only one: a refusal at a time would hide the rest behind the first target that failed.
    let held: BTreeSet<&str> = refused.iter().map(|(target, _)| *target).collect();
    assert!(
        refused.is_empty(),
        "{} of the {} targets do not read the whole of what they answer for of the corpus at \
         {}.\n\n{}",
        held.len(),
        suites.len(),
        under_repository(&corpus, &repository),
        refused
            .iter()
            .map(|(_, refusal)| refusal.as_str())
            .collect::<Vec<&str>>()
            .join("\n\n")
    );

    // The other way a clause goes unheld: not one target failing to read it, but every target
    // stating it answers for something else. Above, each target is held to what it claims; here,
    // the corpus is held to being claimed.
    let unclaimed: Vec<&str> = documents
        .iter()
        .map(String::as_str)
        .filter(|document| !claimed.contains(document))
        .collect();
    assert!(
        unclaimed.is_empty(),
        "{} of {} is a contract for no target: no client states it takes part in {}, so nothing \
         holds anybody to what it declares.\n  \
         Either a client is held to it in the registry, or it says something no client does and \
         does not belong in the corpus.",
        listed(&unclaimed),
        under_repository(&corpus, &repository),
        if unclaimed.len() == 1 { "it" } else { "them" },
    );
}

/// The documents a synthetic client is held to below.
fn two_documents() -> BTreeSet<&'static str> {
    ["retry.json", "request.json"].into_iter().collect()
}

/// What a suite of one file holds, as the walk would have handed it back.
fn suite(written: &str) -> Vec<String> {
    vec![written.to_owned()]
}

/// The rule fires when it should, so a green run says something.
///
/// A name a suite never writes is one it never opened, and the refusal has to survive the two ways
/// a name shows up without anything being read: a line that merely reads like one, and a comment
/// mentioning one in passing.
#[test]
fn a_document_no_line_opens_is_reported_however_the_name_shows_up() {
    let documents = two_documents();
    let every: Vec<&str> = documents.iter().copied().collect();

    assert_eq!(
        unread(
            &documents,
            &suite("func send() { request = request.json(&body) }")
        ),
        every,
        "a builder call reading like a document name was read as a document being opened"
    );
    assert_eq!(
        unread(
            &documents,
            &suite("// what retry.json says, and what request.json says beside it")
        ),
        every,
        "a comment mentioning a document was read as a line opening one"
    );
    assert_eq!(
        unread(&documents, &suite("nothing of the sort")),
        every,
        "a suite naming nothing at all was read as reading something"
    );

    let reading = suite(
        "const corpus = \"../conformance\"\nread(corpus, \"retry.json\")\nread('request.json')",
    );
    assert!(
        unread(&documents, &reading).is_empty(),
        "a suite opening every document was refused"
    );
    assert!(
        names(&reading, "conformance"),
        "a suite saying where the corpus sits was refused"
    );
    assert!(
        !names(
            &suite("the shared conformance corpus says so"),
            "conformance"
        ),
        "prose about the corpus was read as a suite reaching it"
    );
}

/// The rule reads a target's own suite and nothing else.
///
/// Prose, another target's language, the generated half and what the repository does not track are
/// each a way a document name could sit under a client with no line of that client's suite ever
/// opening one.
#[test]
fn only_a_hand_written_source_file_of_the_targets_own_language_counts_as_reading() {
    let documents = two_documents();
    let every: Vec<&str> = documents.iter().copied().collect();
    let opens = "corpus(\"../conformance\", \"retry.json\", \"request.json\")";

    let client = TempDir::new().expect("a temporary directory is available");
    let generated = client.path().join("generated");
    let vendored = client.path().join("node_modules");
    let ignored: BTreeSet<String> = ["node_modules".to_owned()].into_iter().collect();
    for directory in [&generated, &vendored] {
        fs::create_dir(directory).expect("a directory of the client is laid out");
    }

    for (path, written) in [
        (client.path().join("README.md"), opens),
        (client.path().join("suite_test.rb"), opens),
        (generated.join("models_test.go"), opens),
        (vendored.join("someone_elses_test.go"), opens),
        (client.path().join("client_test.go"), "nothing of the sort"),
    ] {
        fs::write(path, written).expect("a file of the client is laid out");
    }

    let walked =
        suite_of(client.path(), &generated, "go", &ignored).expect("the client laid out is walked");
    assert_eq!(
        unread(&documents, &walked),
        every,
        "a document opened only in prose, in another language, in the generated half or in what the \
         repository does not track was read as read"
    );
    assert!(
        !names(&walked, "conformance"),
        "the corpus was reached through something that is not this target's suite"
    );

    fs::write(client.path().join("conformance_test.go"), opens)
        .expect("a suite reading the corpus is laid out");
    let walked =
        suite_of(client.path(), &generated, "go", &ignored).expect("the client laid out is walked");
    assert!(
        unread(&documents, &walked).is_empty(),
        "a suite opening every document of the corpus was refused"
    );
    assert!(
        names(&walked, "conformance"),
        "a suite reaching the corpus was refused"
    );
}

/// A walk above a ceiling is refused naming the ceiling it crossed, rather than read as far as it
/// fits: a suite read halfway is a guard that passes on the half it happened to reach.
#[test]
fn a_client_above_a_ceiling_is_refused_naming_it() {
    let client = TempDir::new().expect("a temporary directory is available");
    let generated = client.path().join("generated");
    let ignored = BTreeSet::new();

    let mut nested = client.path().to_path_buf();
    for depth in 0..=MAX_SUITE_DEPTH {
        nested = nested.join(format!("deeper{depth}"));
    }
    fs::create_dir_all(&nested).expect("a client deeper than is walked is laid out");

    let refused = suite_of(client.path(), &generated, "go", &ignored)
        .expect_err("a client deeper than is walked is refused");
    assert!(
        refused.contains(&MAX_SUITE_DEPTH.to_string()),
        "the refusal does not name the depth walked: {refused}"
    );

    let flat = TempDir::new().expect("a temporary directory is available");
    fs::write(
        flat.path().join("big_test.go"),
        "x".repeat(usize::try_from(MAX_SUITE_FILE_BYTES).expect("the ceiling fits") + 1),
    )
    .expect("a file above the ceiling is laid out");

    let refused = suite_of(flat.path(), &generated, "go", &ignored)
        .expect_err("a file above the ceiling is refused");
    assert!(
        refused.contains(&MAX_SUITE_FILE_BYTES.to_string()),
        "the refusal does not name the ceiling it crossed: {refused}"
    );
}
