# Build app
FROM node:18-slim as build
WORKDIR /app/

ENV API_ENDPOINT http://localhost:8000/api/v1
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# Build nginx image
FROM nginx:alpine
LABEL app.name=app
RUN rm -v /etc/nginx/nginx.conf
COPY self-hosted/docker/frontend/nginx.conf /etc/nginx/
COPY --from=build /app/dist /var/www/

CMD ["nginx", "-g", "daemon off;"]
