//! The artefact the dashboard reads, written as TypeScript.
//!
//! It is committed rather than built. What that buys is a diff in review — the day a snippet
//! changes, the change is visible where changes are looked at — and a frontend build that depends
//! on no Rust toolchain. What it costs is the possibility of the file and the examples disagreeing,
//! which is what the freshness guard beside this exists to remove.
//!
//! The layout is not free-form: the file lands under `frontend/src`, where the frontend's own lint
//! runs Prettier over it. So it is written the way Prettier would write it — objects broken across
//! lines, arrays of pairs one to a line, single quotes unless the value carries more of them than
//! it does double ones, and a trailing comma wherever ES5 allows one.

use crate::Sdk;

/// Everything the dashboard needs, as the module it imports.
pub fn artefact(sdks: &[Sdk]) -> String {
    let mut out = String::new();
    out.push_str(&header());
    out.push_str(TYPES);
    out.push_str("export const HOOK0_SDKS: readonly Hook0Sdk[] = [\n");
    for sdk in sdks {
        out.push_str(&entry(sdk));
    }
    out.push_str("];\n");
    out
}

/// What the file says about itself, so that whoever opens it knows where to make a change stick.
///
/// The two commands are written into it rather than spelled out twice, so that renaming this crate
/// renames what the file tells a reader to run.
fn header() -> String {
    HEADER
        .replace("{regenerate}", crate::REGENERATE)
        .replace("{guard}", crate::GUARD)
}

const HEADER: &str = r#"/**
 * What every Hook0 SDK shows under "Send an event", and what installs it.
 *
 * Generated by `{regenerate}` out of the `examples` directory of
 * each client and of the release inventory. Editing it by hand is caught by
 * `{guard}`, which regenerates it and compares.
 */

"#;

/// The shape of the artefact, which the dashboard and this generator agree on without talking.
///
/// No field is optional and no empty string means "absent": a verification snippet has no labels,
/// so its type carries none rather than carrying empty ones.
const TYPES: &str = r#"export type Hook0SdkSnippet = { readonly body: string };

export type Hook0SdkLabelledSnippet = Hook0SdkSnippet & {
  readonly label: string;
  readonly labelSeparator: string;
};

export type Hook0SdkStringLiteral = {
  readonly open: string;
  readonly close: string;
  /** Applied in order: the backslash first, or it escapes what the others introduced. */
  readonly escape: ReadonlyArray<readonly [string, string]>;
};

export type Hook0Sdk = {
  /** The registry target name: also the CodeMirror language and the URL fragment. */
  readonly target: string;
  readonly displayName: string;
  readonly packageName: string;
  readonly registry: string;
  readonly version: string;
  /** The command that installs it, or the clone instructions when no registry carries it. */
  readonly install: string;
  readonly publishedToRegistry: boolean;
  readonly send: Hook0SdkLabelledSnippet;
  readonly verify: Hook0SdkSnippet;
  readonly stringLiteral: Hook0SdkStringLiteral;
};

"#;

/// The width the frontend's Prettier keeps its lines under.
const PRINT_WIDTH: usize = 100;

/// The length below which Prettier never breaks a line after a key.
///
/// Its own rule, in its own terms: a key narrower than the indent plus three keeps its value on the
/// same line however long that value is, because moving the value one indent to the right buys too
/// little to be worth the line. With the two-space indent this frontend is formatted at, that is
/// `body` and `open` — and it is why those alone run past the margin below.
const SHORT_KEY_CHARS: usize = 5;

/// One SDK, as an element of the list.
fn entry(sdk: &Sdk) -> String {
    let mut out = String::from("  {\n");
    for (key, value) in [
        ("target", &sdk.target),
        ("displayName", &sdk.display_name),
        ("packageName", &sdk.package_name),
        ("registry", &sdk.registry),
        ("version", &sdk.version),
        ("install", &sdk.install),
    ] {
        out.push_str(&field(4, key, value));
    }
    out.push_str(&format!(
        "    publishedToRegistry: {},\n",
        sdk.published_to_registry
    ));

    out.push_str("    send: {\n");
    out.push_str(&field(6, "body", &sdk.send.body));
    out.push_str(&field(6, "label", &sdk.send.label));
    out.push_str(&field(6, "labelSeparator", &sdk.label_separator));
    out.push_str("    },\n");

    out.push_str("    verify: {\n");
    out.push_str(&field(6, "body", &sdk.verify.body));
    out.push_str("    },\n");

    out.push_str("    stringLiteral: {\n");
    out.push_str(&field(6, "open", &sdk.string.open));
    out.push_str(&field(6, "close", &sdk.string.close));
    out.push_str(&escapes(&sdk.string.escape));
    out.push_str("    },\n");

    out.push_str("  },\n");
    out
}

/// One property, laid out the way Prettier would lay it out.
///
/// Public so the suite can hold it to that layout. The frontend's lint runs Prettier as one of its
/// rules over `src/`, and `src/generated` is not ignored, so a file this writes in a layout
/// Prettier disagrees with turns `frontend.check` red — a frontend job failing over a file no
/// frontend developer wrote. Emitting what Prettier would emit is what keeps it green.
///
/// A value that runs past the margin moves onto a line of its own, one indent further in — unless
/// the key is one of the short ones, which keeps its value beside it whatever the width.
pub fn field(indent: usize, key: &str, value: &str) -> String {
    let literal = literal(value);
    let together = format!("{:indent$}{key}: {literal},", "");

    match key.chars().count() < SHORT_KEY_CHARS || width(&together) <= PRINT_WIDTH {
        true => format!("{together}\n"),
        false => format!(
            "{:indent$}{key}:\n{:wider$}{literal},\n",
            "",
            "",
            wider = indent + 2
        ),
    }
}

/// How wide a line is, as the formatter counts it.
fn width(line: &str) -> usize {
    line.chars().count()
}

/// The escaping rules, laid out the way Prettier lays out an array of pairs.
///
/// More than one pair and every one of them a pair: Prettier breaks such an array onto one element
/// per line whatever its width. A single pair is not that array, and goes on one line.
pub fn escapes(rules: &[(String, String)]) -> String {
    let pairs: Vec<String> = rules
        .iter()
        .map(|(from, to)| format!("[{}, {}]", literal(from), literal(to)))
        .collect();

    match pairs.len() {
        1 => format!("      escape: [{}],\n", pairs.join(", ")),
        _ => format!(
            "      escape: [\n{}      ],\n",
            pairs
                .iter()
                .map(|pair| format!("        {pair},\n"))
                .collect::<String>()
        ),
    }
}

/// A value, as a TypeScript string literal.
///
/// The quote is picked the way Prettier picks it — the preferred one unless the value carries more
/// of those than of the other — so that running Prettier over the file changes nothing.
pub fn literal(value: &str) -> String {
    let quote = match value.matches('\'').count() > value.matches('"').count() {
        true => '"',
        false => '\'',
    };

    let mut out = String::with_capacity(value.len() + 2);
    out.push(quote);
    for character in value.chars() {
        match character {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            same if same == quote => {
                out.push('\\');
                out.push(same);
            }
            // Every other control character, which a snippet has no business carrying and which
            // would otherwise land in the file as itself.
            other if other.is_control() => {
                out.push_str(&format!("\\u{:04X}", other as u32));
            }
            other => out.push(other),
        }
    }
    out.push(quote);
    out
}
