{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hook0-play.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hook0-play.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "hook0-play.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "hook0-play.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
{{- end }}
