// @ts-check

// This file is used to define the API sidebar
// It will be populated by the generated API docs

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    {
      type: 'doc',
      id: 'openapi/intro',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'docs/api',
    },
  ],
};

module.exports = sidebars;