//! The header every emitted file carries.
//!
//! It says two things and no more: that the file is generated, and what to run to regenerate it. It
//! carries no date and no version on purpose — either one would rewrite every file of every target
//! on each release of the API, burying the change that actually happened under a diff nobody reads.

use crate::error::{Error, preview};
use crate::limits::Limits;

/// How a language starts a line comment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CommentStyle {
    /// Rust, TypeScript, Go, Java, C#, PHP, Kotlin, Swift.
    DoubleSlash,
    /// Python, Ruby, shell, YAML, TOML.
    Hash,
    /// SQL, Haskell, Lua.
    DoubleDash,
}

impl CommentStyle {
    /// What a line comment starts with.
    pub fn marker(self) -> &'static str {
        match self {
            Self::DoubleSlash => "//",
            Self::Hash => "#",
            Self::DoubleDash => "--",
        }
    }
}

/// The header, naming the command that rewrites the file.
///
/// The command has to survive being read back out of a comment and pasted into a shell, so one
/// carrying a line break — which would leave every line after the first outside the comment, and
/// inside the emitted source — is refused rather than written.
pub fn banner(comment: CommentStyle, command: &str, limits: &Limits) -> Result<String, Error> {
    if command.is_empty() {
        return Err(Error::UnusableCommand {
            reason: "it names nothing to run".to_owned(),
        });
    }
    if command.len() > limits.max_path_bytes {
        return Err(Error::UnusableCommand {
            reason: format!(
                "`{}` is {} bytes long, above the {} accepted",
                preview(command),
                command.len(),
                limits.max_path_bytes
            ),
        });
    }
    if command.chars().any(char::is_control) {
        return Err(Error::UnusableCommand {
            reason: format!(
                "`{}` carries a control character, which would leave part of it outside the comment",
                preview(command)
            ),
        });
    }

    let marker = comment.marker();

    Ok(format!(
        "{marker} Generated by hook0-sdkgen from the OpenAPI snapshot the API crate commits.\n\
         {marker} Do not edit by hand: run `{command}` and commit the result.\n"
    ))
}
